/**
 * LifeLens AI — shared domain types & constants.
 * Used by BOTH the Express API and the React client (npm workspace package).
 *
 * The single most important contract in the app: `AnalysisResult`.
 * LifeLens never returns "just OCR text" — it returns structured,
 * actionable understanding of what the camera saw.
 */

export type Priority = 'HIGH' | 'MEDIUM' | 'LOW';

export type Category =
  | 'Academic'
  | 'Assignment'
  | 'Event'
  | 'Finance'
  | 'Health'
  | 'Personal'
  | 'Travel'
  | 'Other';

export const CATEGORIES: Category[] = [
  'Academic',
  'Assignment',
  'Event',
  'Finance',
  'Health',
  'Personal',
  'Travel',
  'Other',
];

export const PRIORITIES: Priority[] = ['HIGH', 'MEDIUM', 'LOW'];

/** How the capture was understood. Surfaced in the UI so the demo is honest. */
export type AiMode = 'gemini' | 'demo';

/** Everything the AI extracted + decided about one capture. */
export interface AnalysisResult {
  title: string;
  description: string | null;
  category: Category;
  subject: string | null;
  /** ISO date only: YYYY-MM-DD. null when the document has no date. */
  date: string | null;
  /** 24h HH:mm. null when not stated. */
  time: string | null;
  location: string | null;
  priority: Priority;
  /** 0..1 model confidence in the extraction as a whole. */
  confidence: number;
  /** The single most useful next action, in the user's voice. */
  action: string | null;
  /** ISO date (YYYY-MM-DD) on which to remind the user. */
  reminder: string | null;
  /** Concrete checklist items LifeLens derived from the capture. */
  tasks: string[];
  /** Plain-language reasoning, e.g. "High priority because the exam is within 2 days." */
  priorityReason: string | null;
  /** Fields the model was unsure about → the UI marks them editable/uncertain. */
  uncertainFields: string[];
  /** Raw text the model read (OCR-ish), kept for transparency + search. */
  sourceText: string | null;
  aiMode: AiMode;
  /** Only in demo mode: which sample document matched. */
  demoKey?: string;
  note?: string;
}

export interface Capture {
  id: string;
  userId: string;
  /** data:image/...;base64,... (kept so the demo works with zero external storage) */
  imageData?: string | null;
  imageName?: string | null;
  createdAt: string;
  result: AnalysisResult;
  /** true once the user confirmed "Add to my tasks". */
  saved: boolean;
  /** user edited fields after AI analysis (trust layer) */
  edited?: boolean;
}

export interface Task {
  id: string;
  userId: string;
  captureId?: string | null;
  title: string;
  category: Category;
  subject?: string | null;
  priority: Priority;
  priorityReason?: string | null;
  /** ISO date only. */
  dueDate?: string | null;
  /** HH:mm */
  dueTime?: string | null;
  location?: string | null;
  reminder?: string | null;
  action?: string | null;
  description?: string | null;
  done: boolean;
  createdAt: string;
  /** Sub-steps generated by LifeLens. */
  subtasks: Subtask[];
}

export interface Subtask {
  id: string;
  title: string;
  done: boolean;
}

/* ------------------------------- API shapes ------------------------------ */

export interface AnalyzeRequest {
  /** data URL (base64) OR a `demo:<key>` selector for the built-in samples. */
  image?: string;
  demoKey?: string;
  /** free text — used by demo mode's understanding engine */
  text?: string;
  fileName?: string;
}

export interface AnalyzeResponse {
  ok: boolean;
  result?: AnalysisResult;
  /** tasks LifeLens proposes creating from this capture */
  proposedTasks?: string[];
  error?: string;
  fallback?: string;
}

export interface PlanItem {
  rank: number;
  taskId?: string;
  captureId?: string;
  title: string;
  category: Category;
  priority: Priority;
  dueLabel: string;
  reason: string;
  timeSlot?: string | null;
  subtasks?: string[];
}

export interface PlanResponse {
  summary: string;
  recommendation: string;
  items: PlanItem[];
  counts: { high: number; medium: number; low: number; overdue: number };
}

export interface AssistantResponse {
  answer: string;
  intent: string;
  items?: Array<Pick<Task, 'id' | 'title' | 'priority' | 'dueDate' | 'category'>>;
}

export interface HealthResponse {
  ok: boolean;
  aiMode: AiMode;
  model: string;
  hasApiKey: boolean;
  user: { name: string; course: string };
  counts: { captures: number; tasks: number };
  time: string;
}

/* --------------------------------- meta ---------------------------------- */

export const PRIORITY_META: Record<
  Priority,
  { label: string; emoji: string; dot: string; chip: string; ring: string; soft: string }
> = {
  HIGH: {
    label: 'High',
    emoji: '🔴',
    dot: 'bg-rose-500',
    chip: 'bg-rose-50 text-rose-700 border-rose-200',
    ring: 'ring-rose-200',
    soft: 'bg-rose-500/10',
  },
  MEDIUM: {
    label: 'Medium',
    emoji: '🟠',
    dot: 'bg-amber-500',
    chip: 'bg-amber-50 text-amber-700 border-amber-200',
    ring: 'ring-amber-200',
    soft: 'bg-amber-500/10',
  },
  LOW: {
    label: 'Low',
    emoji: '🟢',
    dot: 'bg-emerald-500',
    chip: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    ring: 'ring-emerald-200',
    soft: 'bg-emerald-500/10',
  },
};

export const CATEGORY_EMOJI: Record<Category, string> = {
  Academic: '📚',
  Assignment: '📝',
  Event: '🎓',
  Finance: '💳',
  Health: '💊',
  Personal: '🌱',
  Travel: '✈️',
  Other: '📌',
};

export function priorityRank(p: Priority): number {
  return p === 'HIGH' ? 3 : p === 'MEDIUM' ? 2 : 1;
}

/** YYYY-MM-DD in local time (never UTC — deadlines are a human concept). */
export function localDateKey(d: Date = new Date()): string {
  const p = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

export function addDaysKey(baseKey: string, days: number): string {
  const d = new Date(`${baseKey}T00:00:00`);
  d.setDate(d.getDate() + days);
  return localDateKey(d);
}

/** Whole-day difference (today = 0, tomorrow = 1, yesterday = -1). null if no date. */
export function daysUntil(dateKey: string | null | undefined, from: Date = new Date()): number | null {
  if (!dateKey) return null;
  const target = new Date(`${dateKey}T00:00:00`);
  if (Number.isNaN(target.getTime())) return null;
  const a = new Date(from.getFullYear(), from.getMonth(), from.getDate()).getTime();
  const b = new Date(target.getFullYear(), target.getMonth(), target.getDate()).getTime();
  return Math.round((b - a) / 86400000);
}

export function relativeDueLabel(dateKey: string | null | undefined): string {
  const d = daysUntil(dateKey);
  if (d === null) return 'No date';
  if (d < 0) return d === -1 ? 'Yesterday' : `${Math.abs(d)} days overdue`;
  if (d === 0) return 'Today';
  if (d === 1) return 'Tomorrow';
  if (d < 7) return `in ${d} days`;
  const weeks = Math.round(d / 7);
  return `in ${weeks} week${weeks === 1 ? '' : 's'}`;
}
